from unittest import main
from test_wisard import WisardTestCase
from test_discriminator import DiscriminatorTestCase
from test_cluswisard import ClusWisardTestCase
from test_kernel_canvas import KernelCanvasTestCase
from test_thresholding import ThresholdingTestCase
from test_mean_thresholding import MeanThresholdingTestCase
from test_thermometer import SimpleThermometerTestCase, DynamicThermometerTestCase
from test_bininput import BinInputTestCase
from test_dataset import DataSetTestCase
from test_ramdatahandle import RAMDataHandleTestCase
from test_synthesizer import SynthesizerTestCase
from test_regressionramdatahandle import RegressionRAMDataHandleTestCase
from test_regressionwisard import RegressionWisardTestCase
from test_clusregressionwisard import ClusRegressionWisardTestCase

if __name__ == '__main__':
    main(verbosity=2)
