language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
install:
  - sudo add-apt-repository ppa:jonathonf/gcc-7.3
  - sudo apt-get update
  - sudo apt-get install build-essential
  - gcc --version
  - pip install pybind11
script: python setup.py install
